title = "Learning notes"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "emacs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-159451243-1"
disqusShortname = "3sky"

[params]
    author = "Jakub Wołynko"
    info = "IT Developer"
    description = "Clean and minimal blog about IT"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"
    favicon_32 = "images/f32.png"
    favicon_16 = "images/f16.png"
    footercontent = "Hosted for free by GitHub :*"
    hidecredits = false
    hidecopyright = false
    rtl = false
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/3sky/"
[[params.social]]
    name = "LinkedIN"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/jakubwolynko/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/kuba_wolynko/"
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
