version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.50
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo
      - run:
          name: "Deploy Hugo"
          command: bash deploy.sh       