version: 2.1
jobs:
  build:
    docker: 
      - image: jguyomard/hugo-builder # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: run deploy.sh
          command: |
            sh ./deploy.sh
