name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Hugo
      run: sudo snap install hugo
    - name: Install ruby-dev
      run: sudo apt-get install ruby-dev
    - name: Install depedances for mdl
      run: sudo gem install rake bundler mdl
    - name: Run tests
      run: mdl content/*
    - name: Run deploy.sh
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: sh ./deploy.sh